name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "15 14 * * 3"

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands topics"
  #validate_hassfest:
  #  name: "Hassfest Validation"
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: "actions/checkout@v2"
  #    - uses: home-assistant/actions/hassfest@master
